Digitales/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :variables
  resources :indefinitions
  resources :portraits
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

end

Digitales/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Digitales/app/models/indefinition.rb
class Indefinition < ApplicationRecord
  has_and_belongs_to_many :variable
  has_and_belongs_to_many :portraits
end

Digitales/app/models/portrait.rb
class Portrait < ApplicationRecord
  has_and_belongs_to_many :variable
  has_and_belongs_to_many :indefinitions
end

Digitales/app/models/variable.rb
class Variable < ApplicationRecord
  has_and_belongs_to_many :portraits
  has_and_belongs_to_many :indefinitions
end

Digitales/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Digitales/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @portrait = Portrait.find_by_sql("SELECT * FROM portraits ORDER BY created_at ")
    @indefinitions = Portrait.find_by_sql("SELECT * FROM indefinitions ORDER BY created_at ")
  end

end

Digitales/app/controllers/indefinitions_controller.rb
class IndefinitionsController < ApplicationController
  before_action :set_indefinition, only: [:show, :edit, :update, :destroy]

  # GET /indefinitions
  # GET /indefinitions.json
  def index
    if !params[:letter].blank?
      letter = params[:letter].upcase
    @indefinitions = Indefinition.find_by_sql("SELECT * FROM indefinitions WHERE UPPER(name) LIKE '"+ letter +"%'")
  elsif params[:variable]
  variable = Variable.find(params[:variable])
  @indefinitions = variable.indefinitions
  @variable = variable

  #@indefinitions = Indefinition.find_by_sql('SELECT "indefinitions".* FROM "indefinitions" INNER JOIN "variables_indefinitions" ON "indefinitions"."id" = "variables_indefinitions"."indefinition_id" WHERE "variables_indefinitions"."variable_id" ='+ params[:variable])
else
    @indefinitions = Indefinition.find_by_sql("SELECT * FROM indefinitions ORDER BY name ASC")
  end

  end

  # GET /indefinitions/1
  # GET /indefinitions/1.json
  def show
  end

  # GET /indefinitions/new
  def new
    @indefinition = Indefinition.new
  end

  # GET /indefinitions/1/edit
  def edit
  end

  # POST /indefinitions
  # POST /indefinitions.json
  def create
    @indefinition = Indefinition.new(indefinition_params)

    respond_to do |format|
      if @indefinition.save
        format.html { redirect_to @indefinition, notice: 'Indefinition was successfully created.' }
        format.json { render :show, status: :created, location: @indefinition }
      else
        format.html { render :new }
        format.json { render json: @indefinition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indefinitions/1
  # PATCH/PUT /indefinitions/1.json
  def update
    respond_to do |format|
      if @indefinition.update(indefinition_params)
        format.html { redirect_to @indefinition, notice: 'Indefinition was successfully updated.' }
        format.json { render :show, status: :ok, location: @indefinition }
      else
        format.html { render :edit }
        format.json { render json: @indefinition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indefinitions/1
  # DELETE /indefinitions/1.json
  def destroy
    @indefinition.destroy
    respond_to do |format|
      format.html { redirect_to indefinitions_url, notice: 'Indefinition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indefinition
      @indefinition = Indefinition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indefinition_params
      params.require(:indefinition).permit(:mot, :texte, :url)
    end
end

Digitales/app/controllers/portraits_controller.rb
class PortraitsController < ApplicationController
  before_action :set_portrait, only: [:show, :edit, :update, :destroy]

  # GET /portraits
  # GET /portraits.json
  def index
    if params[:variable]
      variable = Variable.find(params[:variable])
      @portraits = variable.portraits
      @variable = variable
    else
      @portraits = Portrait.all
    end

    if params[:indefinition]
      indefinition = Indefinition.find(params[:indefinition])
      @portraits = indefinition.portraits
      @indefinitions = indefinition
  end
end

  # GET /portraits/1
  # GET /portraits/1.json
  def show
  end

  # GET /portraits/new
  def new
    @portrait = Portrait.new
  end

  # GET /portraits/1/edit
  def edit
  end

  # POST /portraits
  # POST /portraits.json
  def create
    @portrait = Portrait.new(portrait_params)

    respond_to do |format|
      if @portrait.save
        format.html { redirect_to @portrait, notice: 'Portrait was successfully created.' }
        format.json { render :show, status: :created, location: @portrait }
      else
        format.html { render :new }
        format.json { render json: @portrait.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portraits/1
  # PATCH/PUT /portraits/1.json
  def update
    respond_to do |format|
      if @portrait.update(portrait_params)
        format.html { redirect_to @portrait, notice: 'Portrait was successfully updated.' }
        format.json { render :show, status: :ok, location: @portrait }
      else
        format.html { render :edit }
        format.json { render json: @portrait.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portraits/1
  # DELETE /portraits/1.json
  def destroy
    @portrait.destroy
    respond_to do |format|
      format.html { redirect_to portraits_url, notice: 'Portrait was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portrait
      @portrait = Portrait.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portrait_params
      params.require(:portrait).permit(:titre, :auteur, :url, :description)
    end
end

Digitales/app/controllers/variables_controller.rb
class VariablesController < ApplicationController
  before_action :set_variable, only: [:show, :edit, :update, :destroy]

  # GET /variables
  # GET /variables.json
  def index
    @variables = Variable.all
  end

  # GET /variables/1
  # GET /variables/1.json
  def show
  end

  # GET /variables/new
  def new
    @variable = Variable.new
  end

  # GET /variables/1/edit
  def edit
  end

  # POST /variables
  # POST /variables.json
  def create
    @variable = Variable.new(variable_params)

    respond_to do |format|
      if @variable.save
        format.html { redirect_to @variable, notice: 'Variable was successfully created.' }
        format.json { render :show, status: :created, location: @variable }
      else
        format.html { render :new }
        format.json { render json: @variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variables/1
  # PATCH/PUT /variables/1.json
  def update
    respond_to do |format|
      if @variable.update(variable_params)
        format.html { redirect_to @variable, notice: 'Variable was successfully updated.' }
        format.json { render :show, status: :ok, location: @variable }
      else
        format.html { render :edit }
        format.json { render json: @variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variables/1
  # DELETE /variables/1.json
  def destroy
    @variable.destroy
    respond_to do |format|
      format.html { redirect_to variables_url, notice: 'Variable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variable
      @variable = Variable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def variable_params
      params.require(:variable).permit(:titre, :description)
    end
end

Digitales/app/helpers/application_helper.rb
module ApplicationHelper
end

Digitales/app/helpers/indefinitions_helper.rb
module IndefinitionsHelper
end

Digitales/app/helpers/portraits_helper.rb
module PortraitsHelper
end

Digitales/app/helpers/variables_helper.rb
module VariablesHelper
end

Digitales/app/views/home/index.html.erb
<div id="home">

  <section class="section-landing">
    <h1 class="section-title-home">digitales</h1>
    <!-- <p class="paragraphe-home">Digitales est une plateforme qui rassemble des récits témoignant de l’impact du numérique dans la vie de chacun. C’est une invitation a explorer l’aventure numérique au travers d’une multitude de portraits internationaux.</p> -->
    <div class='mouse-container'>
      <div class='mouse'>
        <span class='scroll-down'></span>
      </div>
    </div>
  </section>

  <section class="section-presentation">

  <%= link_to '/portraits' do %>
    <article class="container-portrait">
        <div class="content-text">
          <h2 class="section-title">les portraits</h2>
          <p class="paragraph">Choisissez la dimension qui vous intéresse, vous pourrez ensuite naviguer au travers des portraits ou des indéfinitions liées à ce thème.</p>
        </div>
        <div class="content-img" data-parallax="3" style="transform: translateY(24px);">
          <%= image_tag 'portrait-show.jpg' %>
        </div>
    </article>
  <% end %>

  <%= link_to '/indefinitions' do %>
    <article class="container-indef">
        <div class="content-img" data-parallax="1" style="transform: translateY(24px);">
          <%= image_tag 'indef-show.jpg' %>
        </div>
        <div class="content-text">
          <h2 class="section-title">les indéfinitions</h2>
          <p class="paragraph">Cherchez un terme particulier, une dimensions ou mëme seulement une lettre. Soumettez nous votre mot et votre indéfinition si vous ne la trouver pas ici.</p>
        </div>
    </article>
  <% end %>
  </section>

    <section class="section-news">

      <article class="container-news-portrait">
        <h2 class="section-news-title">Derniers portraits</h2>
        <div class="flex-box-grid-container-portrait">
          <% @portrait.each do |portrait| %>
            <div class="flex-box-grid-content-portrait">
              <%= link_to portrait_path(portrait) do %>
              <div class="portrait-img">
                <% if !portrait.image.nil? %>
                  <%= image_tag(portrait.image) %>
                <%end%>
              </div>
              <span>
                <h3 class="title-description"><%= portrait.name %></h3>
                <p class="title-author">De <%= portrait.auteur %></p>
              </span>
              <% end %>

              <h3 class="title-description"><%= portrait.name %></h3>
              <p class="title-author">De <%= portrait.auteur %></p>
            </div>
          <% end %>
        </div>
      </article>

      <article class="container-news-indef">
        <h2 class="section-news-title">Dernières indéfinitions</h2>
          <div class="flex-box-grid-container">
            <% @indefinitions.each do |indefinition| %>
              <div class="flex-box-grid-content">
                  <h3 class="title-description"><%= indefinition.name %></h3>
                  <div class="paragraph-news"><%= simple_format(indefinition.texte)%></div>
                  <% if !indefinition.url.blank? %>
                    <iframe frameborder="0" width="100%" height="100%" src=" <%= indefinition.url %> "></iframe>
                  <% else indefinition.url.blank? %>
                  <% end %>
                  <h4 class="title-links-container">Dimensions</h4>
                    <div class="container-link-dimensions">
                      <% indefinition.variable.each do |variable| %>
                        <p class="link-dimensions"><%= link_to variable.name.downcase!, "/indefinitions?variable="+variable.id.to_s %></p>
                      <% end %>
                    </div>
              </div>
            <% end %>
          </div>
      </article>

    </section>
</div>

Digitales/app/views/indefinitions/_form.html.erb
<%= form_for(indefinition) do |f| %>
  <% if indefinition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(indefinition.errors.count, "error") %> prohibited this indefinition from being saved:</h2>

      <ul>
      <% indefinition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mot %>
    <%= f.text_field :mot %>
  </div>

  <div class="field">
    <%= f.label :texte %>
    <%= f.text_area :texte %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Digitales/app/views/indefinitions/edit.html.erb
<h1>Editing Indefinition</h1>

<%= render 'form', indefinition: @indefinition %>

<%= link_to 'Show', @indefinition %> |
<%= link_to 'Back', indefinitions_path %>

Digitales/app/views/indefinitions/index.html.erb
<% unless @variable.nil?
  var_intro = @variable.name
end%>

<div id="indef">

  <div class="title">
    <h1 class="section-title"><%= var_intro %> Indefinitions</h1>
    <p class="paragraph">Cherchez un terme particulier, une dimensions ou mëme seulement une lettre. Si ce que vous cherchez n’est pas encore féférencer ici, soumettez nous votre mot et votre indéfinitions.</p>
  </div>
<div id="down">
    <div id="navigate">
      <ul id="alphabet"></ul>
      <div class="btn-reset">
        <%= link_to 'tout voir', "/indefinitions"%>
      </div>
    </div>
  </div>

      <section class="section-indef">
        <article class="container-news-indef">
          <div class="flex-box-grid-container">
            <% @indefinitions.each do |indefinition| %>
              <div class="flex-box-grid-content">
                  <h3 class="title-description"><%= indefinition.name %></h3>
                    <div class="paragraph-news"><%= simple_format(indefinition.texte)%></div>
                  <% if !indefinition.url.blank? %>
                    <iframe frameborder="0" width="100%" height="400px" src=" <%= indefinition.url %> "></iframe>
                  <% else indefinition.url.blank? %>

                  <% end %>
                  <h4 class="title-links-container">Dimensions</h4>
                    <div class="container-link-dimensions">
                      <% indefinition.variable.each do |variable| %>
                        <p class="link-dimensions"><%= link_to variable.name.downcase!, "/indefinitions?variable="+variable.id.to_s %></p>
                      <% end %>
                    </div>
              </div>
            <% end %>
          </div>
        </article>
      </section>

</div>
<%= javascript_include_tag 'wiki', 'data-turbolinks-track': 'reload' %>

Digitales/app/views/indefinitions/new.html.erb
<h1>New Indefinition</h1>

<%= render 'form', indefinition: @indefinition %>

<%= link_to 'Back', indefinitions_path %>

Digitales/app/views/indefinitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mot:</strong>
  <%= @indefinition.mot %>
</p>

<p>
  <strong>Texte:</strong>
  <%= @indefinition.texte %>
</p>

<p>
  <strong>Url:</strong>
  <%= @indefinition.url %>
</p>

<p>
  <strong>Variable:</strong>
  <% @indefinition.variable.each do |variable| %>
        <%= link_to variable.name.downcase!, variable_path(variable) %>
        <% end %>
</p>

<%= link_to 'Edit', edit_indefinition_path(@indefinition) %> |
<%= link_to 'Back', indefinitions_path %>

Digitales/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Digitales</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
        <li><%= link_to "DIGITALES", '/'%></li>
        <li><%= link_to "Dimensions", '/variables'%></li>
        <li><%= link_to "Indéfinitions", '/indefinitions' %></li>
        <li><%= link_to "Portraits", '/portraits'%></li>
      </ul>
    </header>

    <%= yield %>
  </body>
</html>

Digitales/app/views/portraits/_form.html.erb
<%= form_for(portrait) do |f| %>
  <% if portrait.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portrait.errors.count, "error") %> prohibited this portrait from being saved:</h2>

      <ul>
      <% portrait.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %>
    <%= f.text_field :titre %>
  </div>

  <div class="field">
    <%= f.label :auteur %>
    <%= f.text_field :auteur %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Digitales/app/views/portraits/edit.html.erb
<h1>Editing Portrait</h1>

<%= render 'form', portrait: @portrait %>

<%= link_to 'Show', @portrait %> |
<%= link_to 'Back', portraits_path %>

Digitales/app/views/portraits/index.html.erb
<% unless @variable.nil?
  var_intro = @variable.name
end%>

<div id="portrait">

  <section class="title">
    <h1 class="section-title"><%= var_intro %> Portraits</h1>
    <p class="paragraph">Choisissez la dimension qui vous intéresse, vous pourrez ensuite naviguer au travers des portraits ou des indéfinitions liées à ce thème.</p>
  </section>

  <section class="flex-box-grid-container-portrait">
      <% @portraits.each do |portrait| %>
          <div class="flex-box-grid-content-portrait">
            <%= link_to portrait_path(portrait) do %>
            <div class="portrait-img">
              <% if !portrait.image.nil? %>
                <%= image_tag(portrait.image) %>
              <%end%>
            </div>
            <span>
              <h3 class="title-description"><%= portrait.name %></h3>
              <p class="title-author">De <%= portrait.auteur %></p>
            </span>
            <% end %>
          </div>
      <% end %>
  </section>

</div>

Digitales/app/views/portraits/new.html.erb
<h1>New Portrait</h1>

<%= render 'form', portrait: @portrait %>

<%= link_to 'Back', portraits_path %>

Digitales/app/views/portraits/show.html.erb
<div id="show-portrait">
  <div class="btn-return">
    <%= link_to 'Retour aux portraits', portraits_path %>
  </div>
  <section class="section-video">
    <iframe frameborder="0" width="960px" height="550px" src=" <%= @portrait.url %> "></iframe>
  </section>
  <section class="section-content">
    <article class="title">
      <h2 class="section-title"><%= @portrait.name %></h2>
      <h3 class="title-author"><%= @portrait.auteur %></h3>
    </article>
    <article class="description">
      <p class="paragraph"><%= @portrait.description %></p>
    </article>
    <article class="variables-list">
      <h4 class="title-links-container">Dimensions</h4>
        <% @portrait.variable.each do |variable| %>
          <p class="link-dimensions"><%= link_to variable.name.downcase!, "/indefinitions?variable="+variable.id.to_s %></p>
        <% end %>
    </article>
  </section>
</div>

Digitales/app/views/variables/_form.html.erb
<%= form_for(variable) do |f| %>
  <% if variable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(variable.errors.count, "error") %> prohibited this variable from being saved:</h2>

      <ul>
      <% variable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %>
    <%= f.text_field :titre %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Digitales/app/views/variables/edit.html.erb
<h1>Editing Variable</h1>

<%= render 'form', variable: @variable %>

<%= link_to 'Show', @variable %> |
<%= link_to 'Back', variables_path %>

Digitales/app/views/variables/index.html.erb
<div id="var">

  <div class="title">
    <h1 class="section-title">Dimensions</h1>
    <p class="paragraph">Cherchez un terme particulier, une dimensions ou mëme seulement une lettre. Si ce que vous cherchez n’est pas encore féférencer ici, soumettez nous votre mot et votre indéfinitions.</p>
  </div>

  <div class="container-var">
    <ul>
      <% @variables.each do |variable| %>
          <li>
            <em><%= variable.name %></em>
            <%= link_to "portraits", "/portraits?variable="+variable.id.to_s %>
            <%= link_to "indefinitions", "/indefinitions?variable="+variable.id.to_s %>
          </li>
      <% end %>
    </ul>
  </div>

</div>

Digitales/app/views/variables/new.html.erb
<h1>New Variable</h1>

<%= render 'form', variable: @variable %>

<%= link_to 'Back', variables_path %>

Digitales/app/views/variables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titre:</strong>
  <%= @variable.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @variable.description %>
</p>

<%= link_to 'Edit', edit_variable_path(@variable) %> |
<%= link_to 'Back', variables_path %>